import React from "react";
import classes from "./BecomePartner.module.css";

const BecomePartner = () => {
  return (
    <div className={classes.mainContainer}>
      <div className={classes.leftContainer}>
        <div className={classes.heading1Conatiner}>
          <p className={classes.Become}>Become</p>
          <p className={classes.A}>A</p>
          <img
            src="./Images/innovartan_Logo.png"
            alt=""
            className={classes.heading1Image}
          />
        </div>
        <div className={classes.heading2Conatiner}>
          <p className={classes.Become}>Channel</p>
          <p className={classes.A}>Partner</p>
        </div>
        <div className={classes.subHeadingContainer}>
          <div className={classes.subHeadings}>
            <i className={`fa-solid fa-circle-check ${classes.tickIcon}`}></i>
            <p className={classes.subHeading}>
              Earn <strong>1% recurring commission</strong> on the lifetime
              revenue generated by your referrals
            </p>
          </div>
          <div className={classes.subHeadings}>
            <i className={`fa-solid fa-circle-check ${classes.tickIcon}`}></i>
            <p className={classes.subHeading}>
              <strong>Unlimited Earning</strong> Potential
            </p>
          </div>
          <div className={classes.subHeadings}>
            <i className={`fa-solid fa-circle-check ${classes.tickIcon}`}></i>
            <p className={classes.subHeading}>
              Earn <strong>₹10000</strong> on Every Deal
            </p>
          </div>
          <div className={classes.subHeadings}>
            <i className={`fa-solid fa-circle-check ${classes.tickIcon}`}></i>
            <p className={classes.subHeading}>
              Great <strong>After-Sales Support</strong> By{" "}
              <strong style={{ color: "#f46522" }}>Innovartan</strong> Team
            </p>
          </div>
          <div className={classes.subHeadings}>
            <i className={`fa-solid fa-circle-check ${classes.tickIcon}`}></i>
            <p className={classes.subHeading}>
              Join The League of <strong>Innovartan Partners</strong>
            </p>
          </div>
        </div>
      </div>
      <div className={classes.righContainer}>
        <img
          src="./Images/Asserts/patnerProgram.jpeg"
          alt="Kuldeep Kataria"
          className={classes.partnerProgamImage}
        />
      </div>
    </div>
  );
};

export default BecomePartner;
